name:                 bell-fp
version:              0.1.0.0
visibility:           public
id:                   bell-fp-0.1.0.0-inplace
key:                  bell-fp-0.1.0.0-inplace
license:              BSD-3-Clause
copyright:            2025 Author name here
maintainer:           example@example.com
author:               Author name here
homepage:             https://github.com/githubuser/bell-fp#readme
description:
    Please see the README on GitHub at <https://github.com/githubuser/bell-fp#readme>

abi:                  inplace
exposed:              True
exposed-modules:
    CHSH.Clocked CHSH.Contextuality CHSH.Experiment CHSH.Explore
    CHSH.Identity CHSH.LHV CHSH.NoSignaling CHSH.PR CHSH.PRState
    CHSH.Quantum CHSH.Shared CHSH.Superdet CHSH.Util

hidden-modules:       Paths_bell_fp
import-dirs:
    /Users/dcclogin/Code/ideas/bell-fp/dist-newstyle/build/aarch64-osx/ghc-9.4.8/bell-fp-0.1.0.0/build

library-dirs:
    /Users/dcclogin/Code/ideas/bell-fp/dist-newstyle/build/aarch64-osx/ghc-9.4.8/bell-fp-0.1.0.0/build

library-dirs-static:
    /Users/dcclogin/Code/ideas/bell-fp/dist-newstyle/build/aarch64-osx/ghc-9.4.8/bell-fp-0.1.0.0/build

dynamic-library-dirs:
    /Users/dcclogin/Code/ideas/bell-fp/dist-newstyle/build/aarch64-osx/ghc-9.4.8/bell-fp-0.1.0.0/build

data-dir:             /Users/dcclogin/Code/ideas/bell-fp/.
hs-libraries:         HSbell-fp-0.1.0.0-inplace
depends:
    base-4.17.2.1 containers-0.6.7 hmtrx-0.20.2-f74c6e8c mtl-2.2.2
    rndm-1.3.1-bf8a2a51 stm-2.5.1.0 transformers-0.5.6.2

haddock-interfaces:
    /Users/dcclogin/Code/ideas/bell-fp/dist-newstyle/build/aarch64-osx/ghc-9.4.8/bell-fp-0.1.0.0/doc/html/bell-fp/bell-fp.haddock

haddock-html:
    /Users/dcclogin/Code/ideas/bell-fp/dist-newstyle/build/aarch64-osx/ghc-9.4.8/bell-fp-0.1.0.0/doc/html/bell-fp
